### ISSUE TITLE
doesn't seem to work with -SNAPSHOT versions

### ISSUE THREAD

**Issue by ghost** [kota65535/terraform-provider-maven#1]
Thanks for creating this provider, it's exactly what I was looking for to grab AWS Lambda functions published in a Maven repo and use them in a Terraform infrastructure!

I ran into an issue, however, when trying to use a -SNAPSHOT version. The provider fails to download the correct file. I think this has to do with the fact that Maven uses an XML manifest to map the -SNAPSHOT version to the actual time-stamped version number that can be downloaded via HTTP (see https://maven.apache.org/ref/3.2.5/maven-repository-metadata/repository-metadata.html).

To support -SNAPSHOT versions, I think the provider needs to first download and parse the maven-metadata.xml file and use the data therein to determine the correct path to the desired artifact.

I have no experience with Go, otherwise I'd take a stab at a PR. I might still give it a shot when I have some more time, but figured I'd file an issue in case you can do it easily.

**Comment by ghost** [comment]
I just found this Go library that might be useful: https://github.com/navdeepsekhon/go-mvn-dl

**Comment by ghost** [comment]
Well, that was easier than I thought!

**Comment by kota65535** [comment]
@evc-erik I've released v0.1.1, please try it.

**Comment by ghost** [comment]
@kota65535 Thanks for merging and releasing. I just tried it and it works perfectly for me 👍
